<a href="https://colab.research.google.com/github/God-OfTruth/God-OfTruth/blob/master/Image_Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
''

In [ ]:
n=numpy.arange(27)

In [ ]:
n


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
num=numpy.asarray([[552,22,24],[],[]])

/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [ ]:
num

array([list([552, 22, 24]), list([]), list([])], dtype=object)

In [1]:
import cv2

In [4]:
im_gv=cv2.imread("/smallgray.png",0)
im_gv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [5]:
cv2.imwrite("/newsmallgray.png",im_gv)

True

In [10]:
im_gv[0:2]

[0, 2]

In [11]:
im_gv

[0, 2]

In [12]:
im_gv=cv2.imread("/smallgray.png",0)

In [13]:
im_gv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [15]:
im_gv[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [16]:
im_gv.shape

(3, 5)

In [18]:
for i in im_gv:
  print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [19]:
for i in im_gv.flat:
  print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [20]:
im_gv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [23]:
import numpy
im1=numpy.hstack((im_gv,im_gv))
im1

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [24]:
imV=numpy.vstack((im_gv,im_gv))

In [26]:
imvs=numpy.vsplit(imV,3)

In [27]:
imvs

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]